FROM debian:9
MAINTAINER Steve Osselton <steve@iotechsys.com>
RUN apt-get update && apt-get install -y build-essential wget git gcc cmake make
COPY VERSION /iotech-c-utils/
COPY src /iotech-c-utils/src/
COPY include /iotech-c-utils/include/
COPY scripts /iotech-c-utils/scripts
WORKDIR /iotech-c-utils
ENTRYPOINT ["/iotech-c-utils/scripts/linux.sh", "-utest"]
