FROM opensuse/leap:15
MAINTAINER IOTech <support@iotechsys.com>
RUN zypper --non-interactive in git tar glibc-static cmake make wget rpm-build
COPY VERSION /iotech-c-utils/
COPY src /iotech-c-utils/src/
COPY include /iotech-c-utils/include/
COPY scripts /iotech-c-utils/scripts/
WORKDIR /iotech-c-utils
ENTRYPOINT ["/iotech-c-utils/scripts/wrapper.sh", "/iotech-c-utils/scripts/linux.sh", "-utest"]
