FROM fedora:29
MAINTAINER Steve Osselton <steve@iotechsys.com>
RUN yum -y update \
  && yum -y install --setopt=tsflags=nodocs wget git gcc glibc-static cmake3 make valgrind rpm-build \
  && yum clean all && rm -rf /var/cache/yum && mkdir -p /iotech-c-utils/build
COPY VERSION /iotech-c-utils/
COPY src /iotech-c-utils/src/
COPY include /iotech-c-utils/include/
COPY scripts /iotech-c-utils/scripts
WORKDIR /iotech-c-utils
ENTRYPOINT ["/iotech-c-utils/scripts/entrypoint.sh"]
