FROM photon:3.0
MAINTAINER IOTech <support@iotechsys.com>
RUN tdnf remove -y toybox && tdnf update -y && tdnf install -y wget gcc glibc-devel linux-api-headers binutils make git cmake tar gzip rpm rpm-build
COPY VERSION /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest"]
