FROM docker.iotechsys.com/services/zephyr-builder:1.14
MAINTAINER IOTech <support@iotechsys.com>
COPY VERSION /iotech-c-utils/
COPY src /iotech-c-utils/src/
COPY include /iotech-c-utils/include/
COPY scripts /iotech-c-utils/scripts/
WORKDIR /iotech-c-utils
ENTRYPOINT ["/iotech-c-utils/scripts/wrapper.sh", "/iotech-c-utils/scripts/zephyr.sh"]