FROM clearlinux:latest
ENV SYSTEM="clearlinux"
LABEL MAINTAINER="IOTech <support@iotechsys.com>"
RUN swupd bundle-add dev-utils-dev wget doxygen graphviz
COPY VERSION /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest"]
