FROM ubuntu:18.04
ENV SYSTEM="ubuntu-18.04"
LABEL MAINTAINER="IOTech <support@iotechsys.com>"
RUN apt-get update && apt-get install -y lsb-release apt-transport-https curl gnupg build-essential file wget git gcc make doxygen graphviz ruby-dev
RUN gem install public_suffix -v 4.0.7
RUN gem install --no-document fpm
COPY VERSION /iotech-iot/
COPY RELEASE_NOTES.md /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
RUN /iotech-iot/scripts/add_deb_repo.sh
RUN apt-get update && apt-get install -y cmake
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest", "-examples"]
