FROM centos:8
MAINTAINER IOTech <support@iotechsys.com>
RUN yum -y install --setopt=tsflags=nodocs wget git cmake gcc make rpm-build
COPY VERSION /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest", "-examples"]