FROM ubuntu:19.04
MAINTAINER IOTech <support@iotechsys.com>
RUN apt-get update && apt-get install -y build-essential file wget git gcc cmake make valgrind cppcheck lcov gcovr
COPY VERSION /iotech-c-utils/
COPY src /iotech-c-utils/src/
COPY include /iotech-c-utils/include/
COPY scripts /iotech-c-utils/scripts/
WORKDIR /iotech-c-utils
ENTRYPOINT ["/iotech-c-utils/scripts/wrapper.sh", "/iotech-c-utils/scripts/linux.sh", "-cppcheck", "-lcov", "-valgrind", "-utest"]