FROM ubuntu:20.04
LABEL MAINTAINER="IOTech <support@iotechsys.com>"
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime
RUN apt-get update && apt-get install -y build-essential file wget git gcc cmake make valgrind cppcheck lcov gcovr doxygen graphviz uuid-dev
RUN dpkg-reconfigure --frontend noninteractive tzdata
COPY VERSION /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-cppcheck", "-lcov", "-valgrind", "-utest"]
