FROM fedora:33
LABEL MAINTAINER="IOTech <support@iotechsys.com>"
RUN yum -y update && yum -y install --setopt=tsflags=nodocs wget git gcc glibc-static gcc-c++ cmake3 make rpm-build doxygen graphviz
COPY VERSION /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest", "-examples"]