FROM opensuse/leap:15.4
ENV SYSTEM="opensuse-15.4"
LABEL MAINTAINER="IOTech <support@iotechsys.com>"
RUN zypper --non-interactive install git tar cmake gcc-c++ make wget rpm-build doxygen graphviz ruby-devel
RUN gem install public_suffix -v 4.0.7
RUN gem install --no-document fpm
COPY VERSION /iotech-iot/
COPY RELEASE_NOTES.md /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest"]
