FROM fedora:29
MAINTAINER IOTech <support@iotechsys.com>
RUN yum -y update && yum -y install --setopt=tsflags=nodocs wget git gcc glibc-static cmake3 make valgrind rpm-build
COPY VERSION /iotech-c-utils/
COPY src /iotech-c-utils/src/
COPY include /iotech-c-utils/include/
COPY scripts /iotech-c-utils/scripts
WORKDIR /iotech-c-utils
ENTRYPOINT ["/iotech-c-utils/scripts/linux.sh", "-utest"]
