FROM docker.iotechsys.com/services/zephyr-builder:1.14
MAINTAINER IOTech <support@iotechsys.com>
COPY VERSION /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/zephyr.sh"]