FROM ubuntu:26.04
ENV SYSTEM="ubuntu-26.04"
LABEL MAINTAINER="IOTech <support@iotechsys.com>"
ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources && \
    sed -i 's|http://security.ubuntu.com/ubuntu|http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources
RUN apt-get update && apt-get install -y unzip build-essential file wget git gcc cmake make valgrind cppcheck lcov doxygen graphviz python3-pip ruby-dev libxml2-dev libxslt1-dev zlib1g-dev libyaml-dev libcbor-dev
RUN gem install --no-document fpm
RUN pip3 install lxml gcovr --break-system-packages
COPY VERSION /iotech-iot/
COPY RELEASE_NOTES.md /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
COPY sonar-project.properties /iotech-iot/
COPY .git /iotech-iot/.git/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-cppcheck", "-lcov", "-valgrind", "-utest", "-examples"]
