FROM ubuntu:16.04
MAINTAINER IOTech <support@iotechsys.com>
RUN apt-get update && apt-get install -y build-essential file wget git gcc cmake make doxygen graphviz
COPY VERSION /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest", "-examples"]
