FROM alpine:3.9
MAINTAINER Steve Osselton <support@iotechsys.com>
RUN apk add --update --no-cache build-base wget git gcc cmake make openssl-dev
RUN git clone https://github.com/eclipse/paho.mqtt.c.git && cd paho.mqtt.c && make && make install
COPY VERSION /iotech-c-utils/
COPY src /iotech-c-utils/src/
COPY include /iotech-c-utils/include/
COPY scripts /iotech-c-utils/scripts
WORKDIR /iotech-c-utils
ENTRYPOINT ["/iotech-c-utils/scripts/linux.sh", "-utest"]
