FROM opensuse/leap:15
MAINTAINER IOTech <support@iotechsys.com>
RUN zypper --non-interactive in git tar cmake make wget rpm-build doxygen graphviz
COPY VERSION /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest"]
