FROM opensuse/leap:15.3
LABEL MAINTAINER="IOTech <support@iotechsys.com>"
RUN zypper --non-interactive install git tar cmake gcc-c++ make wget rpm-build doxygen graphviz libuuid-devel ruby-devel
RUN gem install --no-document fpm
COPY VERSION /iotech-iot/
COPY RELEASE_NOTES.md /iotech-iot/
COPY src /iotech-iot/src/
COPY include /iotech-iot/include/
COPY scripts /iotech-iot/scripts/
WORKDIR /iotech-iot
ENTRYPOINT ["/iotech-iot/scripts/wrapper.sh", "/iotech-iot/scripts/linux.sh", "-utest"]
